name: Deploy Synapse Workspace

# Controls when the workflow will run
on:
  push:
    branches: [workspace_publish]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs synapse workspace deployment
      - name: Deploy Synapse workspace to UAT
        uses: azure/synapse-workspace-deployment@release-1.7.0
        with:
          TargetWorkspaceName: 'uat-051723'
          TemplateFile: './workspace051723/TemplateForWorkspace.json'
          ParametersFile: './workspace051723/TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: 'synapse-cicd'
          clientId: ${{secrets.CLIENT_ID}}
          clientSecret: ${{secrets.CLIENT_SECRET}}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          tenantId: ${{ secrets.TENANT_ID }}
          operation: 'deploy'
